site_name: bug-bounty-docs
docs_dir: docs
nav:
  - Home: index.md
  - Writeups:
      - Example: writeups/2025-09-15-example.md
      - Template: writeups/template.md
  - Strategies:
      - XSS Strategy: strategies/xss-strategy.md
      - Recon Cheatsheet: strategies/recon-cheatsheet.md
